/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./../src/components/layout/AppHeader.vue')['default']
    AppMobileMenu: typeof import('./../src/components/layout/AppMobileMenu.vue')['default']
    BackTop: typeof import('./../src/components/common/BackTop.vue')['default']
    BaseButton: typeof import('./../src/components/common/BaseButton.vue')['default']
    BaseCard: typeof import('./../src/components/common/BaseCard.vue')['default']
    BaseEmpty: typeof import('./../src/components/common/BaseEmpty.vue')['default']
    BaseLoading: typeof import('./../src/components/common/BaseLoading.vue')['default']
    BasePagination: typeof import('./../src/components/common/BasePagination.vue')['default']
    BaseSkeleton: typeof import('./../src/components/common/BaseSkeleton.vue')['default']
    LangSwitch: typeof import('./../src/components/common/LangSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./../src/components/common/ThemeSwitch.vue')['default']
    VideoControls: typeof import('./../src/components/business/video-player/VideoControls.vue')['default']
    VideoPlayer: typeof import('./../src/components/business/video-player/VideoPlayer.vue')['default']
    VideoProgressBar: typeof import('./../src/components/business/video-player/VideoProgressBar.vue')['default']
  }
}
